import { ShieldCheck, UserRoundCheck, UserRoundX } from 'lucide-react'
import { Button } from '../../components/ui/Button'
import { StatusBadge } from '../../components/ui/StatusBadge'
import type { MemberRequest } from './adminService'

export function MemberRequests({ requests, disabled, pendingAction, onReview }: { requests: MemberRequest[]; disabled?: boolean; pendingAction: string | null; onReview: (id: string, approve: boolean, name: string) => void }) {
  const description = (request: MemberRequest) => request.type === 'create_profile' ? 'New profile' : request.type === 'link_new_device' ? 'New device access' : 'Skill level change'
  return <section className="card overflow-hidden" aria-labelledby="member-requests-title"><div className="border-b border-slate-200 p-5 sm:p-6"><p className="eyebrow">Admin only</p><h2 id="member-requests-title" className="mt-1 text-lg font-bold text-navy-950">Pending member requests</h2><p className="mt-1 text-sm text-slate-600">Verify the person before approving profile, device, or skill changes.</p></div>{requests.length === 0 ? <p className="p-6 text-sm text-slate-500">No pending member requests.</p> : <ul className="divide-y divide-slate-100">{requests.map((request) => { const pending = pendingAction === `member-request-${request.id}`; return <li key={request.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="font-semibold text-slate-900">{request.displayName}</p><p className="mt-1 text-xs font-semibold text-slate-600">{description(request)} · {request.drexelUserId}</p><div className="mt-2 flex flex-wrap gap-2">{request.currentSkillLevel && <StatusBadge kind="skill" value={request.currentSkillLevel} />}{request.requestedSkillLevel && <StatusBadge kind="skill" value={request.requestedSkillLevel} />}<span className="text-xs text-slate-500">Requested {new Date(request.createdAt).toLocaleString()}</span></div></div><div className="flex gap-2"><Button variant="secondary" disabled={disabled || pending} onClick={() => onReview(request.id, false, request.displayName)}><UserRoundX aria-hidden="true" size={16} />Reject</Button><Button disabled={disabled || pending} onClick={() => onReview(request.id, true, request.displayName)}>{pending ? <ShieldCheck aria-hidden="true" size={16} /> : <UserRoundCheck aria-hidden="true" size={16} />}{pending ? 'Saving…' : request.type === 'link_new_device' ? 'Approve and link' : 'Approve'}</Button></div></li> })}</ul>}</section>
}
